### ISSUE TITLE
UNIX support

### ISSUE THREAD

**Issue by stephenlacy** [boazy/any-shell-escape#1]
This breaks on UNIX systems by adding a dollar sign ($) to the front of a string/file path.

Example:

``` js
var escape = require('any-shell-escape');
var url = "/var/www/html/file one.js";
console.log(escape([url]));
```

returns:
`
$'/var/www/html/file one.js'
`
not:
`'/var/www/html/file one.js'`

**Comment by boazy** [comment]
This is the same behavior as shell-escape. I more or less copied the UNIX-code unmodified, so nothing was changed.
Is that wrong?
This works on bash and zsh, but as I've mentioned before it doesn't work on other POSIX-compatible shell - and it never did.

The relevant line of code is:

``` js
s = '$' + util.inspect(s);
```

I guess the reason the original author of shell-escape used the $'string' syntax, is that it allows escaping a single-quote with a backslash, which you cannot do with a normal shell quoted string.

**Comment by boazy** [comment]
I can fix it to make it more portable across shells. I can think of two possible ways for that:
1. Don't use quotes and escape everything with backslashes (this is what the bash autocomplete does).
2. Enclose single quotes in double quotes so `file 'name'.js` becomes `'file '"'"'name'"'"'.js'`.

I think I'll go for option 2, since it's safer.

**Comment by stephenlacy** [comment]
:+1:  Thanks!
